import type { Collection, Lead, Order, Product, Profile } from "./types";

// Demo-mode content. This mirrors supabase/seed.sql so the storefront
// renders fully populated even before a real Supabase project is wired up.
// See lib/supabase/is-configured.ts for how this is used as a fallback.

function img(seed: string, bg: string, fg: string, label: string) {
  return `https://placehold.co/900x1200/${bg}/${fg}?text=${encodeURIComponent(label.replace(/\+/g, " "))}`;
}

// The catalog currently ships 3 flagship 10-target scenes, one per active
// collection. The remaining collections are kept (inactive) so they're easy
// to bring back later without re-authoring copy/hero art.
export const mockCollections: Collection[] = [
  {
    id: "col-wild-west",
    name: "Wild West",
    slug: "wild-west",
    subtitle: "Turn the range into the frontier.",
    description:
      "Saloon standoffs, outlaw hideouts, and frontier justice. Our best-selling theme, reimagined every season.",
    hero_image: img("wild-west", "1a1310", "e4132b", "WILD WEST"),
    sort_order: 1,
    active: true,
    created_at: "2025-01-10T00:00:00Z",
  },
  {
    id: "col-alien-invasion",
    name: "Alien Invasion",
    slug: "alien-invasion",
    subtitle: "First contact. Last stand.",
    description:
      "UFOs, breached outposts, and mothership assaults. Sci-fi themed targets that bring the range into another galaxy.",
    hero_image: img("alien", "0e1512", "39e4a5", "ALIEN INVASION"),
    sort_order: 2,
    active: true,
    created_at: "2025-01-12T00:00:00Z",
  },
  {
    id: "col-zombie-apocalypse",
    name: "Zombie Apocalypse",
    slug: "zombie-apocalypse",
    subtitle: "Survive the outbreak.",
    description:
      "Quarantine zones, last stands, and outbreak protocols. Our most requested collection, refreshed quarterly.",
    hero_image: img("zombie", "141311", "c7d92c", "ZOMBIE APOCALYPSE"),
    sort_order: 3,
    active: true,
    created_at: "2025-01-14T00:00:00Z",
  },
  {
    id: "col-spy-mission",
    name: "Spy Mission",
    slug: "spy-mission",
    subtitle: "Trust no one. Hit every mark.",
    description:
      "Covert ops, double agents, and field training. Sleek, tactical-adjacent design without the cliche camo.",
    hero_image: img("spy", "10141a", "2c9ad9", "SPY MISSION"),
    sort_order: 4,
    active: false,
    created_at: "2025-01-16T00:00:00Z",
  },
  {
    id: "col-classic-series",
    name: "Classic Series",
    slug: "classic-series",
    subtitle: "Precision, without the noise.",
    description:
      "Clean bullseyes, silhouettes, and grids for retailers who want a dependable, no-theme staple alongside the fun stuff.",
    hero_image: img("classic", "121212", "f5f4f2", "CLASSIC SERIES"),
    sort_order: 5,
    active: false,
    created_at: "2025-01-18T00:00:00Z",
  },
  {
    id: "col-limited-editions",
    name: "Limited Editions",
    slug: "limited-editions",
    subtitle: "Here for a season. Gone for good.",
    description:
      "Small-batch drops and seasonal releases. Once they sell out, they don't come back.",
    hero_image: img("limited", "1a1310", "e4132b", "LIMITED EDITIONS"),
    sort_order: 6,
    active: false,
    created_at: "2025-01-20T00:00:00Z",
  },
  {
    id: "col-monster-hunt",
    name: "Monster Hunt",
    slug: "monster-hunt",
    subtitle: "The wild is watching back.",
    description:
      "Apex predators lurking in the fog. A moody wilderness collection for hunters and range-goers who want their targets to feel alive.",
    hero_image: img("monster-hunt", "0d1420", "3d8bc4", "MONSTER HUNT"),
    sort_order: 7,
    active: true,
    created_at: "2026-08-17T00:00:00Z",
  },
];

const byCollection = (slug: string) =>
  mockCollections.find((c) => c.slug === slug)!;

export const mockProducts: Product[] = [
  {
    id: "prod-ww-showdown",
    sku: "WW-SHOWDOWN-10T",
    name: "Wild West Showdown",
    slug: "wild-west-showdown",
    description:
      "A sprawling frontier town scene with 10 numbered outlaws to hit across the saloon, sheriff's office, and dusty main street.",
    collection_id: "col-wild-west",
    collection: byCollection("wild-west"),
    wholesale_price: 26.0,
    msrp: 44.99,
    moq: 15,
    pack_quantity: 15,
    dimensions: '24 × 36 in',
    paper_spec: "28lb premium target paper, matte finish",
    inventory: 200,
    status: "active",
    image_url: "/products/wild-west-showdown.png",
    gallery: [],
    is_new: true,
    is_bestseller: true,
    is_limited: false,
    is_range_favorite: true,
    created_at: "2025-08-01T00:00:00Z",
  },
  {
    id: "prod-za-outbreak",
    sku: "ZA-OUTBREAK-10T",
    name: "Zombie City Outbreak",
    slug: "zombie-city-outbreak",
    description:
      "A ruined downtown overrun by 10 numbered undead, spread across abandoned cars, a police cruiser, and a derelict bus.",
    collection_id: "col-zombie-apocalypse",
    collection: byCollection("zombie-apocalypse"),
    wholesale_price: 26.0,
    msrp: 44.99,
    moq: 15,
    pack_quantity: 15,
    dimensions: '24 × 36 in',
    paper_spec: "28lb premium target paper, matte finish",
    inventory: 200,
    status: "active",
    image_url: "/products/zombie-city-outbreak.png",
    gallery: [],
    is_new: true,
    is_bestseller: true,
    is_limited: false,
    is_range_favorite: true,
    created_at: "2025-08-01T00:00:00Z",
  },
  {
    id: "prod-ai-outpost",
    sku: "AI-OUTPOST-10T",
    name: "Alien Outpost Invasion",
    slug: "alien-outpost-invasion",
    description:
      "A remote alien colony scene with 10 numbered extraterrestrials scattered across towers, a landed ship, and rocky terrain.",
    collection_id: "col-alien-invasion",
    collection: byCollection("alien-invasion"),
    wholesale_price: 26.0,
    msrp: 44.99,
    moq: 15,
    pack_quantity: 15,
    dimensions: '24 × 36 in',
    paper_spec: "28lb premium target paper, matte finish",
    inventory: 200,
    status: "active",
    image_url: "/products/alien-outpost-invasion.png",
    gallery: [],
    is_new: true,
    is_bestseller: true,
    is_limited: false,
    is_range_favorite: true,
    created_at: "2025-08-01T00:00:00Z",
  },
  {
    id: "prod-predators-path",
    sku: "MH-PREDPATH-10T",
    name: "Predator's Path",
    slug: "predators-path",
    description:
      "A misty forest scene with 10 numbered apex predators and game animals stalking through the fog, from black bears to timber wolves.",
    collection_id: "col-monster-hunt",
    collection: byCollection("monster-hunt"),
    wholesale_price: 26.0,
    msrp: 44.99,
    moq: 15,
    pack_quantity: 15,
    dimensions: '24 × 36 in',
    paper_spec: "28lb premium target paper, matte finish",
    inventory: 200,
    status: "active",
    image_url: "/products/predators-path.png",
    gallery: [],
    is_new: true,
    is_bestseller: false,
    is_limited: false,
    is_range_favorite: false,
    created_at: "2026-08-17T00:00:00Z",
  },
];

export const mockRetailers: Profile[] = [
  {
    id: "ret-01",
    email: "orders@ironsightsrange.com",
    role: "retailer",
    retailer_status: "approved",
    business_name: "Iron Sights Range & Supply",
    contact_first_name: "Dana",
    contact_last_name: "Whitfield",
    phone: "(555) 210-4471",
    business_type: "gun_range",
    resale_number: "TX-88213-RS",
    pricing_tier: "standard",
    created_at: "2025-02-01T00:00:00Z",
  },
  {
    id: "ret-02",
    email: "buying@summitoutfitters.com",
    role: "retailer",
    retailer_status: "approved",
    business_name: "Summit Outfitters",
    contact_first_name: "Marcus",
    contact_last_name: " Delgado",
    phone: "(555) 774-2290",
    business_type: "sporting_goods",
    resale_number: "CO-44120-RS",
    pricing_tier: "standard",
    created_at: "2025-03-12T00:00:00Z",
  },
  {
    id: "ret-03",
    email: "purchasing@bullseyedistribution.com",
    role: "retailer",
    retailer_status: "approved",
    business_name: "Bullseye Distribution Co.",
    contact_first_name: "Priya",
    contact_last_name: "Nair",
    phone: "(555) 330-8810",
    business_type: "distributor",
    resale_number: "OH-11239-RS",
    pricing_tier: "volume",
    created_at: "2025-01-20T00:00:00Z",
  },
  {
    id: "ret-04",
    email: "info@rangecoshop.com",
    role: "retailer",
    retailer_status: "pending",
    business_name: "RangeCo Shop",
    contact_first_name: "Trevor",
    contact_last_name: "Aames",
    phone: "(555) 902-1156",
    business_type: "retail_store",
    resale_number: "FL-99213-RS",
    pricing_tier: "standard",
    created_at: "2025-08-10T00:00:00Z",
  },
  {
    id: "ret-05",
    email: "team@crosshairco.com",
    role: "retailer",
    retailer_status: "approved",
    business_name: "Crosshair Co.",
    contact_first_name: "Elena",
    contact_last_name: "Vasquez",
    phone: "(555) 445-7723",
    business_type: "ecommerce_retailer",
    resale_number: "NV-22781-RS",
    pricing_tier: "standard",
    created_at: "2025-04-02T00:00:00Z",
  },
];

const p = (slug: string) => mockProducts.find((x) => x.slug === slug)!;

export const mockOrders: Order[] = [
  {
    id: "ord-1001",
    retailer_id: "ret-01",
    order_number: "PB-10021",
    subtotal: 780.0,
    shipping: 0,
    tax: 62.4,
    total: 842.4,
    status: "delivered",
    tracking_number: "1Z999AA10123456784",
    created_at: "2025-06-02T00:00:00Z",
    items: [
      { id: "oi-1", order_id: "ord-1001", product_id: p("wild-west-showdown").id, quantity: 15, unit_price: 26.0, product: p("wild-west-showdown") },
      { id: "oi-2", order_id: "ord-1001", product_id: p("zombie-city-outbreak").id, quantity: 15, unit_price: 26.0, product: p("zombie-city-outbreak") },
    ],
  },
  {
    id: "ord-1002",
    retailer_id: "ret-01",
    order_number: "PB-10047",
    subtotal: 390.0,
    shipping: 45.0,
    tax: 31.2,
    total: 466.2,
    status: "shipped",
    tracking_number: "1Z999AA10123458812",
    created_at: "2025-07-18T00:00:00Z",
    items: [
      { id: "oi-3", order_id: "ord-1002", product_id: p("alien-outpost-invasion").id, quantity: 15, unit_price: 26.0, product: p("alien-outpost-invasion") },
    ],
  },
  {
    id: "ord-1003",
    retailer_id: "ret-01",
    order_number: "PB-10093",
    subtotal: 390.0,
    shipping: 45.0,
    tax: 31.2,
    total: 466.2,
    status: "processing",
    tracking_number: null,
    created_at: "2025-08-08T00:00:00Z",
    items: [
      { id: "oi-5", order_id: "ord-1003", product_id: p("wild-west-showdown").id, quantity: 15, unit_price: 26.0, product: p("wild-west-showdown") },
    ],
  },
  {
    id: "ord-1004",
    retailer_id: "ret-02",
    order_number: "PB-10058",
    subtotal: 780.0,
    shipping: 0,
    tax: 62.4,
    total: 842.4,
    status: "delivered",
    tracking_number: "1Z999AA10123459931",
    created_at: "2025-07-01T00:00:00Z",
    items: [
      { id: "oi-6", order_id: "ord-1004", product_id: p("zombie-city-outbreak").id, quantity: 15, unit_price: 26.0, product: p("zombie-city-outbreak") },
      { id: "oi-7", order_id: "ord-1004", product_id: p("alien-outpost-invasion").id, quantity: 15, unit_price: 26.0, product: p("alien-outpost-invasion") },
    ],
  },
  {
    id: "ord-1005",
    retailer_id: "ret-05",
    order_number: "PB-10102",
    subtotal: 390.0,
    shipping: 45.0,
    tax: 31.2,
    total: 466.2,
    status: "submitted",
    tracking_number: null,
    created_at: "2025-08-14T00:00:00Z",
    items: [
      { id: "oi-8", order_id: "ord-1005", product_id: p("wild-west-showdown").id, quantity: 15, unit_price: 26.0, product: p("wild-west-showdown") },
    ],
  },
];

export const mockLeads: Lead[] = [
  {
    id: "lead-01",
    business_name: "Sample Gun Range",
    business_type: "gun_range",
    contact_name: "Demo Contact",
    email: "info@example.com",
    phone: "(555) 010-0100",
    website: "https://example.com",
    address: null,
    city: "Toronto",
    region: "ON",
    country: "Canada",
    source: "Demo data",
    notes: "This is placeholder data shown in demo mode. Connect Supabase to see real leads.",
    status: "new",
    created_at: "2026-08-01T00:00:00Z",
  },
];
